events {
    worker_connections 1024;
}

http {
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    upstream task6_app {
        server task6-app:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://task6_app;
            proxy_read_timeout 120s;
        }
    }
}